title: Michael's Site
author: Michael J.
email: mjucan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Everything superficial and unimportant about Michael J.

# social links
twitter_username: jack # DO NOT include the @ character, or else the build will fail!
github_username:  slobodan002 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
