title: Michael's Site
author: Michael J., EBHS
email: mjucan@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Nobody is ever going to need to read this and I would prefer it not show up in searches

# social links
twitter_username: jack # DO NOT include the @ character, or else the build will fail!
github_username:  slobodan002 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
